SELECT COHORTS.name AS COHORT_name, COUNT(STUDENTS.*) AS STUDENT_COUNT
FROM COHORTS
JOIN STUDENTS ON COHORTS.id = STUDENTS.cohort_id
GROUP BY COHORTS.name
HAVING COUNT(STUDENTS.*) >= 18
ORDER BY STUDENT_COUNT;

